### ISSUE TITLE
Support for charaters "[" and "]" in text line

### ISSUE THREAD

**Issue by seaspeak** [SamLangTen/KaraokeShow#11]
Can you support "[]" in text line, for example:
>[00:03.43]cooking ::= [U] the process

Everything following "[" is discarded.

I'm not sure whether an universal lrc format exist, but [SONY's implementation](http://docs.esupport.sony.com/portable/NWZE353_E354_E355_guide/eng/contents/03/05/11/11.html#l3_notes) might be a good reference.

**Comment by SamLangTen** [comment]
This bug has been fixed in pull request:  #14
