### ISSUE TITLE
How to automatically load DeskLyricsDisplay? 

### ISSUE THREAD

**Issue by seaspeak** [SamLangTen/KaraokeShow#12]
Is that possible to load DeskLyricsDisplay automatically after MusicBee startup? Now I have to manually open it.

Is this something to do with
>KaraokeShow plugin is different from MusicBee plugin, so it usually can not be loaded directly by MusicBee.

Project [MusicBee-DesktopLyrics](https://github.com/cqjjjzr/MusicBee-DesktopLyrics) can be loaded automatically.

**Comment by SamLangTen** [comment]
#14
